language: node_js
  
install:
  - npm install newman
  
before script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  
script:
  - node_modules/.bin/newman run tests/Collection Test.postman_collection.json
